# Generated by Django 5.0.2 on 2024-03-22 16:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.FloatField(default=0)),
                ('saldo_devedor', models.FloatField(default=0)),
                ('receber', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('num_telefone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('D', 'DEVENDO'), ('P', 'PAGO'), ('I', 'INATIVO')], default='I', max_length=1)),
                ('saldo_devedor', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('ciclo', models.IntegerField()),
                ('lucro', models.FloatField()),
                ('quantidade', models.IntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.marca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.FloatField()),
                ('valor_venda', models.FloatField()),
                ('lucro', models.FloatField()),
                ('parcelas', models.IntegerField()),
                ('saldo_devedor', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'EM ABERTO'), ('P', 'PAGO')], max_length=1)),
                ('data', models.DateField(default=datetime.datetime(2024, 3, 22, 16, 35, 52, 311407, tzinfo=datetime.timezone.utc))),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                ('produtos', models.ManyToManyField(to='vendas.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime(2024, 3, 22, 16, 35, 52, 318888, tzinfo=datetime.timezone.utc))),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=datetime.datetime(2024, 3, 22, 16, 35, 52, 321340, tzinfo=datetime.timezone.utc))),
                ('data_vencimento', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('D', 'DEVENDO'), ('P', 'PAGO'), ('V', 'VENCIDO')], default='D', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendas', models.ManyToManyField(to='vendas.venda')),
            ],
        ),
    ]
