# Generated by Django 5.0.2 on 2024-03-25 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 0, 27, 38, 758741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='data_emissao',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 0, 27, 38, 758065, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 0, 27, 38, 755714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 0, 27, 38, 746586, tzinfo=datetime.timezone.utc)),
        ),
    ]
